name: aoc23
description: Dart Advent of Code 2023
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.17.0